FROM ubuntu

MAINTAINER sushantpedhapalli@gmail.com
ENV container docker
WORKDIR /opt
RUN apt-get update
RUN apt-get install openjdk-8-jdk wget vim unzip tar make gcc g++ git gnupg gnupg2 gnupg1 -y
RUN wget https://updates.jenkins-ci.org/download/war/2.205/jenkins.war
RUN java -version
RUN mkdir /opt/maven
RUN wget https://www-eu.apache.org/dist/maven/maven-3/3.6.2/binaries/apache-maven-3.6.2-bin.tar.gz
RUN tar -xvzf apache-maven-3.6.2-bin.tar.gz
RUN mv apache-maven-3.6.2/* maven/. && rm -rf apache-maven-3.6.2
RUN touch /etc/profile.d/variable && echo "export PATH=/opt/maven/bin:${PATH}" >> /etc/profile.d/variable
RUN apt-get update && apt-get install curl wget -y
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -
RUN apt-get install nodejs -y
RUN curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update && apt-get install yarn
RUN node --version && npm --version && npm install -g @angular/cli
RUN ng --version
ENTRYPOINT ["java", "-jar"]
CMD ["jenkins.war"]
EXPOSE 8080
